# Form implementation generated from reading ui file 'c:\Users\marco\Desktop\VScode\banco\gui\login.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_formLogin(object):
    def setupUi(self, formLogin):
        formLogin.setObjectName("formLogin")
        formLogin.resize(458, 426)
        formLogin.setMinimumSize(QtCore.QSize(458, 426))
        formLogin.setMaximumSize(QtCore.QSize(458, 426))
        font = QtGui.QFont()
        font.setPointSize(12)
        formLogin.setFont(font)
        formLogin.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(parent=formLogin)
        self.label.setGeometry(QtCore.QRect(130, 20, 181, 161))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\marco\\Desktop\\VScode\\banco\\gui\\../82392.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=formLogin)
        self.label_2.setGeometry(QtCore.QRect(150, 170, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=formLogin)
        self.label_3.setGeometry(QtCore.QRect(40, 230, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=formLogin)
        self.label_4.setGeometry(QtCore.QRect(30, 260, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txtUsuario = QtWidgets.QLineEdit(parent=formLogin)
        self.txtUsuario.setGeometry(QtCore.QRect(120, 240, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtUsuario.setFont(font)
        self.txtUsuario.setStyleSheet("")
        self.txtUsuario.setObjectName("txtUsuario")
        self.txtClave = QtWidgets.QLineEdit(parent=formLogin)
        self.txtClave.setGeometry(QtCore.QRect(120, 270, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtClave.setFont(font)
        self.txtClave.setStyleSheet("")
        self.txtClave.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtClave.setObjectName("txtClave")
        self.btnAcceder = QtWidgets.QPushButton(parent=formLogin)
        self.btnAcceder.setGeometry(QtCore.QRect(190, 310, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        self.btnAcceder.setFont(font)
        self.btnAcceder.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnAcceder.setStyleSheet("background-color: rgb(170, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius : 8px;")
        self.btnAcceder.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Spanish, QtCore.QLocale.Country.Spain))
        self.btnAcceder.setObjectName("btnAcceder")
        self.lblMensaje = QtWidgets.QLabel(parent=formLogin)
        self.lblMensaje.setGeometry(QtCore.QRect(110, 370, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblMensaje.setFont(font)
        self.lblMensaje.setStyleSheet("color: rgb(255, 131, 131);")
        self.lblMensaje.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblMensaje.setObjectName("lblMensaje")

        self.retranslateUi(formLogin)
        QtCore.QMetaObject.connectSlotsByName(formLogin)

    def retranslateUi(self, formLogin):
        _translate = QtCore.QCoreApplication.translate
        formLogin.setWindowTitle(_translate("formLogin", "Inicio de sesión."))
        self.label_2.setText(_translate("formLogin", "Inicio de Sesión"))
        self.label_3.setText(_translate("formLogin", "Usuario:"))
        self.label_4.setText(_translate("formLogin", "Contraseña: "))
        self.txtUsuario.setPlaceholderText(_translate("formLogin", "Ingrese usuario"))
        self.txtClave.setPlaceholderText(_translate("formLogin", "Ingrese contraseña"))
        self.btnAcceder.setText(_translate("formLogin", "ACCEDER"))
        self.lblMensaje.setText(_translate("formLogin", "mensaje"))
