# Form implementation generated from reading ui file 'c:\Users\marco\Desktop\VScode\banco\gui\main.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=main)
        self.centralwidget.setObjectName("centralwidget")
        main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(parent=self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuCreditos = QtWidgets.QMenu(parent=self.menubar)
        self.menuCreditos.setObjectName("menuCreditos")
        main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=main)
        self.statusbar.setObjectName("statusbar")
        main.setStatusBar(self.statusbar)
        self.actionDesarrolladores = QtGui.QAction(parent=main)
        self.actionDesarrolladores.setObjectName("actionDesarrolladores")
        self.btnRegistrar_Transferencias = QtGui.QAction(parent=main)
        self.btnRegistrar_Transferencias.setObjectName("btnRegistrar_Transferencias")
        self.btnReportar_Transferencias = QtGui.QAction(parent=main)
        self.btnReportar_Transferencias.setObjectName("btnReportar_Transferencias")
        self.btnHistorial_de_Transferencias = QtGui.QAction(parent=main)
        self.btnHistorial_de_Transferencias.setObjectName("btnHistorial_de_Transferencias")
        self.menuArchivo.addAction(self.btnRegistrar_Transferencias)
        self.menuArchivo.addAction(self.btnReportar_Transferencias)
        self.menuArchivo.addAction(self.btnHistorial_de_Transferencias)
        self.menuCreditos.addAction(self.actionDesarrolladores)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuCreditos.menuAction())

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Banco Real Transferencias"))
        self.menuArchivo.setTitle(_translate("main", "Archivo"))
        self.menuCreditos.setTitle(_translate("main", "Creditos"))
        self.actionDesarrolladores.setText(_translate("main", "Desarrolladores"))
        self.btnRegistrar_Transferencias.setText(_translate("main", "Registrar Transferencias"))
        self.btnRegistrar_Transferencias.setShortcut(_translate("main", "Ctrl+R"))
        self.btnReportar_Transferencias.setText(_translate("main", "Reportar Transferencias"))
        self.btnReportar_Transferencias.setShortcut(_translate("main", "Ctrl+T"))
        self.btnHistorial_de_Transferencias.setText(_translate("main", "Historial de Transferencias"))
        self.btnHistorial_de_Transferencias.setShortcut(_translate("main", "Ctrl+B"))
